"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.deletePerson = exports.updatePerson = exports.createPerson = exports.deleteKudo = exports.updateKudo = exports.createKudo = void 0;
// Manually Overridden
exports.createKudo = "\n  mutation CreateKudo($input: CreateKudoInput!, $condition: ModelKudoConditionInput) {\n    createKudo(input: $input, condition: $condition) {\n      id\n      createdAt\n      receiver {\n        kudosReceived {\n          items {\n            id\n          }\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.updateKudo = "\n  mutation UpdateKudo($input: UpdateKudoInput!, $condition: ModelKudoConditionInput) {\n    updateKudo(input: $input, condition: $condition) {\n      id\n      giverId\n      receiverId\n      message\n      kudoVerb\n      dataSourceApp\n      createdAt\n      link\n      metadata\n      giver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      receiver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.deleteKudo = "\n  mutation DeleteKudo($input: DeleteKudoInput!, $condition: ModelKudoConditionInput) {\n    deleteKudo(input: $input, condition: $condition) {\n      id\n      giverId\n      receiverId\n      message\n      kudoVerb\n      dataSourceApp\n      createdAt\n      link\n      metadata\n      giver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      receiver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.createPerson = "\n  mutation CreatePerson($input: CreatePersonInput!, $condition: ModelPersonConditionInput) {\n    createPerson(input: $input, condition: $condition) {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.updatePerson = "\n  mutation UpdatePerson($input: UpdatePersonInput!, $condition: ModelPersonConditionInput) {\n    updatePerson(input: $input, condition: $condition) {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.deletePerson = "\n  mutation DeletePerson($input: DeletePersonInput!, $condition: ModelPersonConditionInput) {\n    deletePerson(input: $input, condition: $condition) {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          link\n          metadata\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
