"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.onDeletePerson = exports.onUpdatePerson = exports.onCreatePerson = exports.onDeleteKudo = exports.onUpdateKudo = exports.onCreateKudo = void 0;
exports.onCreateKudo = "\n  subscription OnCreateKudo {\n    onCreateKudo {\n      id\n      giverId\n      receiverId\n      message\n      kudoVerb\n      dataSourceApp\n      metadata {\n        ... on GitHubMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n          owner\n          repo\n          team\n          item\n        }\n        ... on TwitterMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n        }\n      }\n      createdAt\n      giver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      receiver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.onUpdateKudo = "\n  subscription OnUpdateKudo {\n    onUpdateKudo {\n      id\n      giverId\n      receiverId\n      message\n      kudoVerb\n      dataSourceApp\n      metadata {\n        ... on GitHubMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n          owner\n          repo\n          team\n          item\n        }\n        ... on TwitterMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n        }\n      }\n      createdAt\n      giver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      receiver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.onDeleteKudo = "\n  subscription OnDeleteKudo {\n    onDeleteKudo {\n      id\n      giverId\n      receiverId\n      message\n      kudoVerb\n      dataSourceApp\n      metadata {\n        ... on GitHubMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n          owner\n          repo\n          team\n          item\n        }\n        ... on TwitterMetadata {\n          dataSourceId\n          dataSourceApp\n          url\n        }\n      }\n      createdAt\n      giver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      receiver {\n        id\n        username\n        email\n        dataSourceApp\n        kudosGiven {\n          nextToken\n        }\n        kudosReceived {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n";
exports.onCreatePerson = "\n  subscription OnCreatePerson {\n    onCreatePerson {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onUpdatePerson = "\n  subscription OnUpdatePerson {\n    onUpdatePerson {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onDeletePerson = "\n  subscription OnDeletePerson {\n    onDeletePerson {\n      id\n      username\n      email\n      dataSourceApp\n      kudosGiven {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      kudosReceived {\n        items {\n          id\n          giverId\n          receiverId\n          message\n          kudoVerb\n          dataSourceApp\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
