"use strict";
/* eslint-disable @typescript-eslint/no-empty-interface */
/* eslint-disable @typescript-eslint/ban-types */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
exports.__esModule = true;
